### ISSUE TITLE
Injection not working inside a constructor

### ISSUE THREAD

**Issue by samuelcardoso** [thiagobustamante/typescript-ioc#5]
```typescript
constructor(@Inject protected myObject: MyObject)
{
  super(myObject);
}
```

myObject is undefined.

**Comment by thiagobustamante** [comment]
I known @samuelcardoso, and we debugged this issue in his computer. The problem was related to a bug in typescript-rest dependency control.  To ensure that this behavior is working fine here, I also include a test case [here](https://github.com/thiagobustamante/typescript-ioc/commit/059a0ee613738c18fd1018028025b3d605ac357c).

**Comment by himalayazest** [comment]
@samuelcardoso @thiagobustamante This is still not resolved. Facing same issue, please add some documentation for the root cause found and the workaround for this.
